Repository betterbettor/bet-better-server, pull requests merged in 2023-10, with the labels that each got.

#19 Feat/swagger
  src/routes/base.ts
  src/routes/match.ts
  src/types/types.d.js
  tsconfig.json
Labels: documentation, Status: Ready for Review

#30 add winston logging
  .gitignore
  package.json
  src/app.ts
  src/services/cronService.ts
  src/utils/logger.ts
  yarn.lock
Labels: Type: Feature, Status: Ready for Review

#31 Feat/db index
  src/controllers/matchController.ts
  src/interfaces/odds.interface.ts
  src/models/matchModel.ts
  src/models/oddsModel.ts
  src/services/cronService.ts
  src/services/oddsService.ts
Labels: Type: Feature, Status: Ready for Review

#26 created dockerfile
  .dockerignore
  Dockerfile
Labels: Type: Feature, Status: Ready for Review

#29 support using multiple api keys
  src/app.ts
  src/config/config.ts
  src/services/apiFootballService.ts
Labels: Type: Feature, Status: Ready for Review

#36 handled fetch for multiple pages
  src/services/apiFootballService.ts
  src/services/cronService.ts
Labels: Type: Fix, Status: Ready for Review
